#!/usr/bin/env bash
# Installs and configures Nginx in Holberton sandbox

# Update and install nginx
apt-get update -y
apt-get install -y nginx

# Overwrite the default file used by Nginx sandbox config
echo "Holberton School for the win!" > /var/www/html/index.html

# Restart Nginx using service (no systemctl allowed)
service nginx restart
