#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu server

# Update package list and install nginx
apt-get update -y
apt-get install -y nginx

# Overwrite the actual default index.html served by Nginx
echo "Holberton School" > /var/www/html/index.html

# Restart nginx using service
service nginx restart
